'use strict';

const fs=require('node:fs');
const crypto=require('node:crypto');
const {buildDiagnosisEvidence,buildDiagnosisInputManifest,classifyFailureDeterministically,normalizeDiagnosisResult,createDiagnosisReceipt,formatDiagnosisMarkdown}=require('./codex-safe-core/diagnosis-platform');
const {GitLabDiagnoseClient}=require('./gitlab');
const {runCodexDiagnosis}=require('./codex');
const {rankFailedJobEvidence,formatRankedFailureBlocks}=require('./failure-causality');

const MAX_LOCAL_LOG_BYTES=32*1024*1024;
const MAX_FAILED_JOBS=12;
function digest(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function appError(code,message){return Object.assign(new Error(message),{code});}
function readLocalLog(file){const stat=fs.statSync(file);if(!stat.isFile())throw appError('ELOGFILE','--log must reference a regular file');if(stat.size>MAX_LOCAL_LOG_BYTES)throw appError('ELOGSIZE',`Local log exceeds ${MAX_LOCAL_LOG_BYTES} bytes`);return fs.readFileSync(file,'utf8');}
function deterministicDiagnosis(prior,evidence){const classification=prior.classification||'unknown',actions={source:['Inspect the first compiler/linker error and the affected source change; reproduce with the same build configuration.'],test:['Inspect the first failing assertion and its fixture/input; compare it with the changed behavior.'],dependency:['Verify the lockfile/registry/artifact version that the failed job resolved and restore a reproducible dependency set.'],infra:['Verify runner/network/storage availability and retry only after the infrastructure condition is cleared.'],flaky:['Re-run the isolated failing test under the same revision and collect repeated evidence before changing product code.'],unknown:['Inspect the earliest error in the compact evidence and collect the missing build/test context before changing code.']}[classification];return normalizeDiagnosisResult({classification,rootCause:`Deterministic-only mode classified the supplied failure evidence as ${classification}; model root-cause synthesis was intentionally disabled.`,confidence:prior.confidence,primaryEvidence:(evidence.log.text.match(/^\d+: .*$/gm)||[]).slice(0,5),relatedFailures:[],affectedFiles:[],recommendedActions:actions,retryRecommended:classification==='infra'||classification==='flaky'},evidence);}
async function collectArtifacts(client,project,jobs,specs){const texts=[],meta=[];for(const job of jobs){for(const spec of specs||[]){let text;try{text=await client.getArtifactText(project,job.id,spec.path);}catch(error){if(error.status===404)continue;throw error;}if(text===null)continue;const bounded=String(text).slice(0,256*1024),name=`job-${job.id}/${spec.path}`,sha=digest(text);texts.push(Object.freeze({kind:spec.kind,name,text:bounded,digest:sha}));meta.push(Object.freeze({kind:spec.kind,name,digest:sha}));}}return Object.freeze({texts:Object.freeze(texts),meta:Object.freeze(meta)});}
async function collectGitLab(options,client){const project=options.project;if(options.jobId){const job=await client.getJob(project,options.jobId);if(String(job.status)!=='failed')throw appError('EJOBSTATE',`Job ${job.id} is ${job.status}; only failed jobs are diagnosed`);const trace=await client.getTrace(project,job.id),pipelineId=Number(job.pipeline?.id||0)||null,commitSha=String(job.commit?.id||job.pipeline?.sha||''),artifacts=await collectArtifacts(client,project,[job],options.artifacts),changedPaths=await client.changedPaths(project,commitSha);return{log:`===== FAILED JOB ${job.id} ${job.name||''} stage=${job.stage||''} =====\n${trace}`,job:{projectId:Number(project)||null,pipelineId,jobId:Number(job.id),commitSha,jobName:String(job.name||`job ${job.id}`)},artifactTexts:artifacts.texts,artifactMeta:artifacts.meta,changedPaths,mrIid:options.mrIid||0};}
  const pipeline=await client.getPipeline(project,options.pipelineId),jobsResult=await client.listPipelineJobs(project,options.pipelineId);if(!jobsResult.complete)throw appError('EGITLABPAGINATION','Failed-job enumeration exceeded the configured GitLab page limit');const failed=jobsResult.items.filter(job=>String(job.status)==='failed').sort((a,b)=>Number(a.id)-Number(b.id));if(!failed.length)throw appError('EPIPELINESTATE',`Pipeline ${options.pipelineId} has no failed jobs`);if(failed.length>MAX_FAILED_JOBS)throw appError('EJOBLIMIT',`Pipeline has ${failed.length} failed jobs; maximum bounded diagnosis set is ${MAX_FAILED_JOBS}`);const entries=[];for(const job of failed){const trace=await client.getTrace(project,job.id);entries.push({job,trace});}const ranked=rankFailedJobEvidence(entries),rankedJobs=ranked.map(item=>item.job),commitSha=String(pipeline.sha||failed[0]?.commit?.id||''),artifacts=await collectArtifacts(client,project,rankedJobs,options.artifacts),changedPaths=await client.changedPaths(project,commitSha);return{log:formatRankedFailureBlocks(ranked),job:{projectId:Number(project)||null,pipelineId:Number(pipeline.id||options.pipelineId),jobId:null,commitSha,jobName:`pipeline ${pipeline.id||options.pipelineId}: ${failed.length} failed job(s)`},artifactTexts:artifacts.texts,artifactMeta:artifacts.meta,changedPaths,mrIid:options.mrIid||0,failedJobs:ranked.map(item=>({id:item.job.id,name:item.job.name,stage:item.job.stage,status:item.job.status,causalRank:item.causalRank,stageRank:item.stageRank,classification:item.classification,confidence:item.confidence,cascade:item.cascade,duplicateOf:item.duplicateOf,signature:item.signature}))};}
async function resolvePublishMr(client,project,commitSha,explicit){if(explicit)return explicit;const mrs=await client.mergeRequestsForCommit(project,commitSha),open=mrs.filter(item=>String(item.state)==='opened');return Number(open[0]?.iid||0)||0;}
async function runDiagnosis(options,{client=null,runCodexFn=runCodexDiagnosis}={}){
  let source;
  if(options.logFile){const log=readLocalLog(options.logFile);source={log,job:{projectId:null,pipelineId:null,jobId:null,commitSha:`local:${digest(log).slice(0,24)}`,jobName:'local log'},artifactTexts:[],artifactMeta:[],changedPaths:[],mrIid:0};}
  else{const token=String(process.env[options.gitlabTokenEnv]||'').trim();if(!token)throw appError('EGITLABTOKEN',`GitLab token environment variable ${options.gitlabTokenEnv} is missing`);client=client||new GitLabDiagnoseClient({baseUrl:options.gitlabUrl,token});source=await collectGitLab(options,client);}
  const evidence=buildDiagnosisEvidence({log:source.log,job:source.job,artifacts:source.artifactMeta}),prior=classifyFailureDeterministically(evidence.log.text);
  let diagnosis,model='',codexVersion='',usage={},durationMs=0,requestEstimate=null,modelEvidence=null,modelRoutingManaged=false,modelRegistryRevision='';
  if(options.deterministicOnly){diagnosis=deterministicDiagnosis(prior,evidence);model='deterministic';}
  else{const result=await runCodexFn({evidence,deterministic:prior,changedPaths:source.changedPaths,artifactTexts:source.artifactTexts,options});diagnosis=result.diagnosis;model=result.model;codexVersion=result.codexVersion;usage=result.usage;durationMs=result.durationMs;requestEstimate=result.requestEstimate;modelEvidence=result.modelEvidence||null;modelRoutingManaged=Boolean(result.modelRoutingManaged);modelRegistryRevision=result.modelRegistryRevision||'';}
  const inputManifest=buildDiagnosisInputManifest({evidence,deterministic:prior,changedPaths:source.changedPaths,artifactTexts:source.artifactTexts,model});
  const receipt=createDiagnosisReceipt({evidence,inputManifest,diagnosis,model,codexVersion}),markdown=formatDiagnosisMarkdown(diagnosis,evidence,receipt.createdAt);
  let publishedMr=0;if(options.publish){publishedMr=await resolvePublishMr(client,options.project,evidence.subject.commitSha,source.mrIid);if(!publishedMr)throw appError('EMRNOTFOUND','No open merge request is associated with the failed commit; pass --mr explicitly');await client.upsertDiagnosisNote(options.project,publishedMr,markdown);}
  return Object.freeze({schemaVersion:2,diagnosis,receipt,evidence:{version:evidence.version,digest:evidence.digest,inputManifestDigest:inputManifest.digest,subject:evidence.subject,log:{digest:evidence.log.digest,originalLines:evidence.log.originalLines,includedLines:evidence.log.includedLines,bytes:evidence.log.bytes,truncated:evidence.log.truncated},artifacts:evidence.artifacts,changedPaths:Object.freeze(source.changedPaths.slice(0,200)),failedJobs:Object.freeze(source.failedJobs||[])},execution:{mode:options.deterministicOnly?'deterministic':'codex',model,codexVersion,usage,durationMs,requestEstimate,modelRoutingContractVersion:options.deterministicOnly?null:1,modelRoutingManaged,modelRegistryRevision,modelEvidence,inputManifest:{version:inputManifest.version,digest:inputManifest.digest,promptContractVersion:inputManifest.promptContractVersion}},publication:{mrIid:publishedMr||null},markdown});
}
module.exports={MAX_LOCAL_LOG_BYTES,MAX_FAILED_JOBS,readLocalLog,deterministicDiagnosis,collectArtifacts,collectGitLab,resolvePublishMr,runDiagnosis};
